# Generated by Django 2.1.5 on 2019-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluginId', models.IntegerField()),
                ('host_ip', models.CharField(max_length=50)),
                ('detail', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluginId', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('risk', models.CharField(max_length=100)),
                ('files', models.SlugField()),
                ('description', models.SlugField()),
            ],
        ),
    ]
